workflows:
  ios-build:
    name: Build para 3uTools
    max_build_duration: 60
    instance_type: mac_mini_m2
    scripts:
      - name: Build para Simulador
        script: |
          xcodebuild build \
            -workspace "SR Software.xcworkspace" \
            -scheme "SR Software" \
            -configuration Release \
            -sdk iphonesimulator \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY=""
    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/Products/Release-iphonesimulator/*.app
