workflows:
  ios-build:
    name: Build para 3uTools
    max_build_duration: 60
    instance_type: mac_mini_m2
    scripts:
      - name: Build Executável
        script: |
          # Limpa builds antigos
          xcodebuild clean -workspace "SR Software.xcworkspace" -scheme "SR Software"
          
          # Gera o arquivo .app sem precisar de assinatura ou certificados
          xcodebuild build \
            -workspace "SR Software.xcworkspace" \
            -scheme "SR Software" \
            -configuration Release \
            -sdk iphoneos \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            AD_HOC_CODE_SIGNING_ALLOWED=YES
    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/Products/Release-iphoneos/*.app
