workflows:
  ios-build:
    name: Build Forçado 3uTools
    instance_type: mac_mini_m2
    scripts:
      - name: Build
        script: |
          xcodebuild build \
            -workspace "SR Software.xcworkspace" \
            -scheme "SR Software" \
            -configuration Release \
            -sdk iphoneos \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            PROVISIONING_PROFILE_SPECIFIER="" \
            -allowProvisioningUpdates
    artifacts:
      - build/ios/iphoneos/*.app
